apiVersion: "networking.k8s.io/v1"
kind: "Ingress"
metadata:
  name: "tsmc-lb"
  namespace: "default"
spec:
  defaultBackend:
    service:
      name: "grafana-nodeport"
      port:
        number: 3000
status:
  loadBalancer: {}
