apiVersion: apps/v1
kind: Deployment
metadata:
  name: "apc-deployment"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: Always
          env: 
            - name: NATS_SERVICE_CONNECTION
              value: 'nats://tsmc-nats:4222'
            - name: NODE_CONFIG
              value: '{"mongodb": {"uri": "mongodb://tsmc-mongodb:27017/"}}'
            - name: MONGO_USER
              value: 'root'
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tsmc-mongodb
                  key: mongodb-root-password
                  optional: false
          ports:
            - containerPort: {{ .Values.service.port }}

