apiVersion: apps/v1
kind: Deployment
metadata:
  name: "apc-deployment"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}
          imagePullPolicy: Always
          env: 
            - name: NATS_SERVICE_CONNECTION
              value: tsmc-nats:4222
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: 
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}