{
 "title": "log dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Avg Process Complete Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (info) (rate({app=\"apc-simulator\"} | pattern `<service> | <time> | <info> | <msg> | <jsdata>` | info =~ \"info\" | msg =~ \"process.*\"  [1m] )) "
    }
   ]
  },
  {
   "title": "Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "last_over_time({app=\"apc-simulator\"} | pattern `<service> | <time> | <info> | <msg> | <jsdata>` | info =~ \"info\" | msg =~ \"receive.*\" | line_format \"{{.msg}}\" | pattern `<_> <type> <_>: <fac>`  | line_format \"type={{.type}} fac={{.fac}}\" | logfmt | unwrap fac | __error__ = \"\" [1h]) by (type) ",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "APC Info Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"apc-simulator\"} | pattern `<service> | <time> | <info> | <msg> | <jsdata>` | info =~ \"info\" | line_format \"\\033[96;1m{{ printf \\\"%-20.20s\\\" .service }}\\033[0m \\033[92;1m{{ .info }}\\033[0m\\n\\033[1;37m{{ .msg }}\\033[0m\\n\\n\" ",
     "maxLines": 100,
     "resolution": 2
    }
   ]
  },
  {
   "title": "APC Error Log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"apc-simulator\"} | pattern `<service> | <time> | <info> | <msg> | <jsdata>` | info !~ \"info\" | line_format \"\\033[93;1m{{ .service }}\\033[0m \\033[91;1m{{ .info }}\\033[0m \\033[1;37m{{ .msg }}\\033[0m\" "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total [1h])",
     "legendFormat": "{{job}}"
    }
   ]
  }
 ]
}